### ISSUE TITLE
Minimize bootstrap assets

### ISSUE THREAD

**Issue by jdnavarro** [UnkindPartition/tasty-html#13]
There is no need to import all bootstrap JavaScript, CSS and fonts in the HTML files. This would minimize the size of tasty HTML files. I guess this is only about configuring the grunt build process.

Originally coming from #10.

**Comment by 414owen** [comment]
Bootstrap has been thoroughly minimized in https://github.com/UnkindPartition/tasty-html/pull/23 :)
