### ISSUE TITLE
Update bootstrap version

### ISSUE THREAD

**Issue by jdnavarro** [UnkindPartition/tasty-html#18]
Upstream commits from 3.2.0 to 3.3.1 would need to be merged in https://github.com/jdnavarro/bootstrap. Then the version numbers laying around would need to be bumped.

This is a good chance to centralize the version numbers somewhere to facilitate further updates.

**Comment by 414owen** [comment]
Closed in favour of removing bootstrap with https://github.com/UnkindPartition/tasty-html/pull/23 :)
