### ISSUE TITLE
Support tasty-1.5

### ISSUE THREAD

**Issue by Bodigrim** [UnkindPartition/tasty-html#24]
```
tasty-html-0.4.2.1$ cabal build --constraint 'tasty>=1.5'
[1 of 2] Compiling Paths_tasty_html
[2 of 2] Compiling Test.Tasty.Runners.Html

Test/Tasty/Runners/Html.hs:94:48: error: [GHC-83865]
    • Couldn't match type: Traversal
                             (Compose (StateT Int IO) (Const Summary))
                     with: [SummaryTraversal]
      Expected: OptionSet
                -> TestName -> [SummaryTraversal] -> SummaryTraversal
        Actual: OptionSet
                -> TestName -> SummaryTraversal -> SummaryTraversal
    • In the expression: runGroup
      In a record update at fields ‘Tasty.foldSingle’, ‘Tasty.foldGroup’,
      with type constructor ‘Tasty.TreeFold’
      and data constructor ‘Tasty.TreeFold’.
      In the first argument of ‘Tasty.foldTestTree’, namely
        ‘Tasty.trivialFold
           {Tasty.foldSingle = runTest statusMap, Tasty.foldGroup = runGroup}’
   |
94 |                           , Tasty.foldGroup  = runGroup
   |                                                ^^^^^^^^
```

**Comment by andreasabel** [comment]
I added bound `tasty < 1.5` to all published versions of `tasty-html`.

**Comment by andreasabel** [comment]
@414owen : Could you upgrade `tasty-html` to `tasty-1.5` and publish to Hackage?  
Otherwise, `tasty-html` will fall out of Stackage:
- https://github.com/commercialhaskell/stackage/issues/7242

**Comment by 414owen** [comment]
:scream:

Yes, will do.

**Comment by 414owen** [comment]
I've published `tasty-html 0.4.2.2`, which supports `tasty >=1.5 && < 1.6` :+1:

**Comment by andreasabel** [comment]
https://hackage.haskell.org/package/tasty-html-0.4.2.2
- https://github.com/commercialhaskell/stackage/pull/7262

**Comment by andreasabel** [comment]
@414owen : Would you like to take over Stackage maintainership for `tasty-html`?  
You would then be notified of issues with this package in stackage snapshots...

Currently, stackage maintainership is with Roman, but he is still unavailable:
https://github.com/commercialhaskell/stackage/blob/0f63f2afc10877a17195c32e18ec6e91bd029bbc/build-constraints.yaml#L1436-L1448

**Comment by 414owen** [comment]
Yes, this seems sensible. I can take over stackage maintainership.
I don't use stack myself, but I just read the MAINTAINERS section in the stackage repo, and I can certainly see how it keeps the ecosystem moving forwards.

I've added myself [here](https://github.com/commercialhaskell/stackage/pull/7264).
